In [12]:
#In this below Code File, we are going to build Various Classification Models and then we are going to Suggest the best Model based on the Accuracy of Results.
#In order to build various classifications we need import some of the files to our code
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

In [13]:
eda2 = pd.read_csv(r'C:\Users\aijaz\TITANIC.csv')

In [107]:
eda2.head(30)

PassengerId  Survived  Pclass  \
1              2         1       1   
3              4         1       1   
6              7         0       1   
10            11         1       3   
11            12         1       1   
21            22         1       2   
23            24         1       1   
27            28         0       1   
52            53         1       1   
54            55         0       1   
62            63         0       1   
66            67         1       2   
75            76         0       3   
88            89         1       1   
92            93         0       1   
96            97         0       1   
97            98         1       1   
102          103         0       1   
110          111         0       1   
118          119         0       1   
123          124         1       2   
124          125         0       1   
136          137         1       1   
137          138         0       1   
139          140         0       1   
148          149         0       2   
151          152         1       1   
170          171         0       1   
174          175         0       1   
177          178         0       1   

                                                  Name     Sex   Age  SibSp  \
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
6                              McCarthy, Mr. Timothy J    male  54.0      0   
10                     Sandstrom, Miss. Marguerite Rut  female   4.0      1   
11                            Bonnell, Miss. Elizabeth  female  58.0      0   
21                               Beesley, Mr. Lawrence    male  34.0      0   
23                        Sloper, Mr. William Thompson    male  28.0      0   
27                      Fortune, Mr. Charles Alexander    male  19.0      3   
52            Harper, Mrs. Henry Sleeper (Myna Haxtun)  female  49.0      1   
54                      Ostby, Mr. Engelhart Cornelius    male  65.0      0   
62                         Harris, Mr. Henry Birkhardt    male  45.0      1   
66                        Nye, Mrs. (Elizabeth Ramell)  female  29.0      0   
75                             Moen, Mr. Sigurd Hansen    male  25.0      0   
88                          Fortune, Miss. Mabel Helen  female  23.0      3   
92                         Chaffee, Mr. Herbert Fuller    male  46.0      1   
96                           Goldschmidt, Mr. George B    male  71.0      0   
97                     Greenfield, Mr. William Bertram    male  23.0      0   
102                          White, Mr. Richard Frasar    male  21.0      0   
110                     Porter, Mr. Walter Chamberlain    male  47.0      0   
118                           Baxter, Mr. Quigg Edmond    male  24.0      0   
123                                Webber, Miss. Susan  female  32.5      0   
124                        White, Mr. Percival Wayland    male  54.0      0   
136                       Newsom, Miss. Helen Monypeny  female  19.0      0   
137                        Futrelle, Mr. Jacques Heath    male  37.0      1   
139                                 Giglio, Mr. Victor    male  24.0      0   
148           Navratil, Mr. Michel ("Louis M Hoffman")    male  36.5      0   
151                  Pears, Mrs. Thomas (Edith Wearne)  female  22.0      1   
170                          Van der hoef, Mr. Wyckoff    male  61.0      0   
174                            Smith, Mr. James Clinch    male  56.0      0   
177                         Isham, Miss. Ann Elizabeth  female  50.0      0   

     Parch       Ticket      Fare        Cabin Embarked  
1        0     PC 17599   71.2833          C85        C  
3        0       113803   53.1000         C123        S  
6        0        17463   51.8625          E46        S  
10       1      PP 9549   16.7000           G6        S  
11       0       113783   26.5500         C103        S  
21       0       248698   13

In [108]:
eda2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 183 entries, 1 to 889
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  183 non-null    int64  
 1   Survived     183 non-null    int64  
 2   Pclass       183 non-null    int64  
 3   Name         183 non-null    object 
 4   Sex          183 non-null    object 
 5   Age          183 non-null    float64
 6   SibSp        183 non-null    int64  
 7   Parch        183 non-null    int64  
 8   Ticket       183 non-null    object 
 9   Fare         183 non-null    float64
 10  Cabin        183 non-null    object 
 11  Embarked     183 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 18.6+ KB


In [109]:
eda2.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   183.000000  183.000000  183.000000  183.000000  183.000000   
mean    455.366120    0.672131    1.191257   35.674426    0.464481   
std     247.052476    0.470725    0.515187   15.643866    0.644159   
min       2.000000    0.000000    1.000000    0.920000    0.000000   
25%     263.500000    0.000000    1.000000   24.000000    0.000000   
50%     457.000000    1.000000    1.000000   36.000000    0.000000   
75%     676.000000    1.000000    1.000000   47.500000    1.000000   
max     890.000000    1.000000    3.000000   80.000000    3.000000   

            Parch        Fare  
count  183.000000  183.000000  
mean     0.475410   78.682469  
std      0.754617   76.347843  
min      0.000000    0.000000  
25%      0.000000   29.700000  
50%      0.000000   57.000000  
75%      1.000000   90.000000  
max      4.000000  512.329200

In [110]:
eda2.isnull()

PassengerId  Survived  Pclass   Name    Sex    Age  SibSp  Parch  Ticket  \
1          False     False   False  False  False  False  False  False   False   
3          False     False   False  False  False  False  False  False   False   
6          False     False   False  False  False  False  False  False   False   
10         False     False   False  False  False  False  False  False   False   
11         False     False   False  False  False  False  False  False   False   
..           ...       ...     ...    ...    ...    ...    ...    ...     ...   
871        False     False   False  False  False  False  False  False   False   
872        False     False   False  False  False  False  False  False   False   
879        False     False   False  False  False  False  False  False   False   
887        False     False   False  False  False  False  False  False   False   
889        False     False   False  False  False  False  False  False   False   

      Fare  Cabin  Embarked  
1    False  False     False  
3    False  False     False  
6    False  False     False  
10   False  False     False  
11   False  False     False  
..     ...    ...       ...  
871  False  False     False  
872  False  False     False  
879  False  False     False  
887  False  False     False  
889  False  False     False  

[183 rows x 12 columns]

In [111]:
eda2.isnull().values.any()

False

In [112]:
eda2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 183 entries, 1 to 889
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  183 non-null    int64  
 1   Survived     183 non-null    int64  
 2   Pclass       183 non-null    int64  
 3   Name         183 non-null    object 
 4   Sex          183 non-null    object 
 5   Age          183 non-null    float64
 6   SibSp        183 non-null    int64  
 7   Parch        183 non-null    int64  
 8   Ticket       183 non-null    object 
 9   Fare         183 non-null    float64
 10  Cabin        183 non-null    object 
 11  Embarked     183 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 18.6+ KB


In [113]:
print ("There is no null values in the dataset")

There is no null values in the dataset


In [114]:
eda2.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   183.000000  183.000000  183.000000  183.000000  183.000000   
mean    455.366120    0.672131    1.191257   35.674426    0.464481   
std     247.052476    0.470725    0.515187   15.643866    0.644159   
min       2.000000    0.000000    1.000000    0.920000    0.000000   
25%     263.500000    0.000000    1.000000   24.000000    0.000000   
50%     457.000000    1.000000    1.000000   36.000000    0.000000   
75%     676.000000    1.000000    1.000000   47.500000    1.000000   
max     890.000000    1.000000    3.000000   80.000000    3.000000   

            Parch        Fare  
count  183.000000  183.000000  
mean     0.475410   78.682469  
std      0.754617   76.347843  
min      0.000000    0.000000  
25%      0.000000   29.700000  
50%      0.000000   57.000000  
75%      1.000000   90.000000  
max      4.000000  512.329200

In [115]:
eda2.shape

(183, 12)

In [169]:
X = eda2.iloc[:,[5,6,7]].values

In [170]:
y = eda2["Survived"]

In [171]:
#SPLITTING 
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=42,stratify=y)

In [172]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)

In [173]:
eda2 =eda2[~eda2.isin([np.nan, np.inf, -np.inf]).any(1)]


In [174]:
X_train

array([[ 1.24158831, -0.67606514, -0.60932879],
       [-0.76281707, -0.67606514, -0.60932879],
       [-0.01116505, -0.67606514,  2.04076784],
       [ 0.80312463,  0.89378103, -0.60932879],
       [-0.76281707, -0.67606514,  0.71571953],
       [ 0.8657623 ,  0.89378103, -0.60932879],
       [-0.26171572, -0.67606514, -0.60932879],
       [ 0.17674795,  0.89378103,  0.71571953],
       [ 0.17674795, -0.67606514, -0.60932879],
       [ 1.36686365, -0.67606514,  0.71571953],
       [-0.44962873,  0.89378103,  0.71571953],
       [-1.26391841, -0.67606514,  0.71571953],
       [ 2.11851566,  0.89378103,  0.71571953],
       [-0.01116505, -0.67606514, -0.60932879],
       [-2.01557043,  2.46362721,  0.71571953],
       [-0.63754173, -0.67606514, -0.60932879],
       [ 0.99103764,  0.89378103,  0.71571953],
       [ 1.49213898,  0.89378103, -0.60932879],
       [-0.44962873, -0.67606514, -0.60932879],
       [-0.82545473, -0.67606514,  0.71571953],
       [-0.38699106, -0.67606514, -0.609

In [175]:
#TRAIN ON TRAINING SET
# 1. KNN CLASSIFICATION
from sklearn.neighbors import KNeighborsClassifier

In [176]:
knn = KNeighborsClassifier(n_neighbors=3)

In [177]:
knn.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=3)

In [178]:
#EVALUATE
knn.score(X_test,y_test)

0.6739130434782609

In [179]:
#PREDICT
knn.predict(X_test)

array([1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1], dtype=int64)

In [180]:
# 2. LOGISTIC REGRESSION 
from sklearn.linear_model import LogisticRegression

In [181]:
lr = LogisticRegression()
#fitting the model
lr.fit(X_train,y_train)

LogisticRegression()

In [182]:
#EVALUATE
lr.score(X_test,y_test)

0.6956521739130435

In [183]:
#PREDICT
lr.predict(X_test)

array([1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1], dtype=int64)

In [184]:
# 3. DECISION TREE
from sklearn.tree import DecisionTreeClassifier

In [185]:
tree = DecisionTreeClassifier()

In [186]:
tree.fit(X_train,y_train)

DecisionTreeClassifier()

In [187]:
#EVALUATE
tree.score(X_test,y_test)

0.6956521739130435

In [188]:
#PREDICT
tree.predict(X_test)

array([1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1,
       1, 1], dtype=int64)

In [189]:
# 4. RANDOM FOREST
from sklearn.ensemble import RandomForestClassifier

In [190]:
forest = RandomForestClassifier(n_estimators=100)

In [191]:
forest.fit(X_train,y_train)

RandomForestClassifier()

In [195]:
#EVALUATE
forest.score(X_test,y_test)

0.5869565217391305

In [193]:
#PREDICT
forest.predict(X_test)

array([1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 1], dtype=int64)

In [194]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_predict))

              precision    recall  f1-score   support

           0       0.60      0.20      0.30        15
           1       0.71      0.94      0.81        31

    accuracy                           0.70        46
   macro avg       0.65      0.57      0.55        46
weighted avg       0.67      0.70      0.64        46



In [ ]:
#CONCLUSION 
#On Evaluating the different classifications and by Comparing them with each the score obtain from them is: 0.6956521739130435  which is (69.56%)
#And this Scores are obtain by Logistic Regression and Decision Tree
#So we can undertake Logistic Regression and Decision Tree into account of more accurate in the given TITANIC dataset